renames:
  # --- Scene 1: Renamed
  # > no filters set so every video file is renamed
  1: "/[VIDEOS]/Girls Who Squat.mp4"

  # --- Scene 2: Renamed
  # > no filters set so every video file is renamed
  2: "/[VIDEOS]/Butt Stuff 101.mp4"

  # --- Scene 3: Renamed
  # > no filters set so every video file is renamed
  3: "/[VIDEOS]/First time to LP Juicy sweet ass Mandy Muse in a beautifull DP full of gapes and balls deep action AA029.mp4"

  # --- Scene 4: Renamed
  # > no filters set so every video file is renamed
  4: "/[VIDEOS]/Madison Wants it Rough.mp4"

  # --- Scene 5: Renamed
  # > no filters set so every video file is renamed
  # ***WARNING***: Since this scene does not have a title, it will be named ".{extension}"
  5: "/[VIDEOS]/.mov"

  # --- Scene 6: Renamed
  # > no filters set so every video file is renamed
  6: "/[VIDEOS]/A Horny Christmas Carol.mp4"
