version: 1
disable_existing_loggers: true
formatters:
  simple:
    format: "[%(asctime)s] %(levelname)-8s %(message)s"
handlers:
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: "${plugin_dir}\\logs\\lily.log" # NOTE: Ensure the logs folder exists
    encoding: "utf-8"
    mode: "a"
    maxBytes: 10485760 # 10 MB
    backupCount: 3
  rename_log_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: "${plugin_dir}\\logs\\lily.rename.log" # NOTE: Ensure the logs folder exists
    encoding: "utf-8"
    mode: "a"
    maxBytes: 10485760 # 10 MB
    backupCount: 5
  dry_run_log_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: "${plugin_dir}\\logs\\lily.dry-run.log" # NOTE: Ensure the logs folder exists
    encoding: "utf-8"
    mode: "a"
    maxBytes: 10485760 # 10 MB
    backupCount: 5
root:
  level: DEBUG
  handlers:
    - file
loggers:
  rename:
    level: INFO
    handlers:
      - rename_log_file
  dry-run:
    level: INFO
    handlers:
      - dry_run_log_file
