version: 0.0.1
rename_rules:
  - name: "Basic rename rule"
    template_file_dir: "/[VIDEOS]"
    # WARNING: Scenes without a title will be named just ".{extension}"
    template_file_name: "${title}"

    # field_settings:
    #   title:
    #     fallback_to_source_video_file_name: true

    # post_templating_settings:
    #   file_name:
    #     whitespace_character: "."
